// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanGiay.Data;

#nullable disable

namespace WebBanGiay.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250417015950_d28")]
    partial class d28
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClssLib.Anh_San_Pham", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("San_PhamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("anh_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("San_PhamID");

                    b.ToTable("anh_San_Phams");
                });

            modelBuilder.Entity("ClssLib.Anh_San_Pham_San_Pham_Chi_Tiet", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Anh_San_PhamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("San_Pham_Chi_TietID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("Anh_San_PhamID");

                    b.HasIndex("San_Pham_Chi_TietID");

                    b.ToTable("anh_San_Pham_San_Pham_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.Chat_Lieu", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ten_chat_lieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("chat_Lieus");
                });

            modelBuilder.Entity("ClssLib.Co_Giay", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ten_loai_co_giay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("co_Giays");
                });

            modelBuilder.Entity("ClssLib.Danh_Muc", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ten_danh_muc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("danh_Mucs");
                });

            modelBuilder.Entity("ClssLib.De_Giay", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ten_de_giay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("de_Giays");
                });

            modelBuilder.Entity("ClssLib.Dia_Chi", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Tai_KhoanID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("dia_chi_chi_tiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("huyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_default")
                        .HasColumnType("bit");

                    b.Property<int>("loai_dia_chi")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("tinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Tai_KhoanID");

                    b.ToTable("dia_Chis");
                });

            modelBuilder.Entity("ClssLib.Hoa_Don", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Giam_GiaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Ship")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dia_chi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("discount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email_nguoi_nhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ghi_chu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("loai_hoa_don")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("nguoi_sua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nguoi_tao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt_nguoi_nhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_nguoi_nhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("thoi_gian_nhan_hang")
                        .HasColumnType("datetime2");

                    b.Property<double>("tong_tien")
                        .HasColumnType("float");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Giam_GiaID");

                    b.ToTable("hoa_Dons");
                });

            modelBuilder.Entity("ClssLib.Hoa_Don_Chi_Tiet", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Hoa_DonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("San_Pham_Chi_TietID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("gia")
                        .HasColumnType("float");

                    b.Property<string>("ma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("nguoi_sua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nguoi_tao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("phuongThucthanhtoan")
                        .HasColumnType("int");

                    b.Property<int>("so_luong")
                        .HasColumnType("int");

                    b.Property<string>("tensp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("thanh_tien")
                        .HasColumnType("float");

                    b.Property<int?>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Hoa_DonID");

                    b.HasIndex("San_Pham_Chi_TietID");

                    b.ToTable("don_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.Kich_Thuoc", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ten_kich_thuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("kich_Thuocs");
                });

            modelBuilder.Entity("ClssLib.Kieu_Dang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ten_kieu_dang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("kieu_Dangs");
                });

            modelBuilder.Entity("ClssLib.Loai_Giay", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ten_loai_giay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("loai_Giays");
                });

            modelBuilder.Entity("ClssLib.Mau_Sac", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma_mau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("mau_Sacs");
                });

            modelBuilder.Entity("ClssLib.Mui_Giay", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ten_mui_giay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("mui_Giays");
                });

            modelBuilder.Entity("ClssLib.Phieu_Giam_Gia", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("gia_tri_giam")
                        .HasColumnType("int");

                    b.Property<double?>("gia_tri_toi_thieu")
                        .HasColumnType("float");

                    b.Property<int>("kieu_giam_gia")
                        .HasColumnType("int");

                    b.Property<int>("loai_phieu_giam_gia")
                        .HasColumnType("int");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_bat_dau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ngay_ket_thuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("nguoi_sua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("so_luong")
                        .HasColumnType("int");

                    b.Property<int?>("so_tien_giam_toi_da")
                        .HasColumnType("int");

                    b.Property<string>("ten_phieu_giam_gia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("phieu_Giam_Gias");
                });

            modelBuilder.Entity("ClssLib.Phieu_Giam_Gia_Tai_Khoan", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Phieu_Giam_GiaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Tai_KhoanID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("nguoi_sua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Phieu_Giam_GiaID");

                    b.HasIndex("Tai_KhoanID");

                    b.ToTable("phieu_Giam_Gia_Tai_Khoans");
                });

            modelBuilder.Entity("ClssLib.Phuong_Thuc_Thanh_Toan", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_phuong_thuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("phuong_Thuc_Thanh_Toans");

                    b.HasData(
                        new
                        {
                            ID = new Guid("b9fc7a66-a407-4e3e-baf4-ff4c2a490951"),
                            ma = "TTM",
                            ten_phuong_thuc = "Tiền mặt"
                        },
                        new
                        {
                            ID = new Guid("e25880ae-fce0-4955-875e-781f17d147e2"),
                            ma = "CK",
                            ten_phuong_thuc = "Chuyển khoản"
                        },
                        new
                        {
                            ID = new Guid("e686e410-925c-4c87-acc3-bc9732adac6b"),
                            ma = "ALL",
                            ten_phuong_thuc = "Cả 2"
                        });
                });

            modelBuilder.Entity("ClssLib.San_Pham", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Chat_LieuID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Co_GiayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Danh_MucID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("De_GiayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Kieu_DangID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Loai_GiayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Mui_GiayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("nguoi_sua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nguoi_tao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_san_pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Chat_LieuID");

                    b.HasIndex("Co_GiayID");

                    b.HasIndex("Danh_MucID");

                    b.HasIndex("De_GiayID");

                    b.HasIndex("Kieu_DangID");

                    b.HasIndex("Loai_GiayID");

                    b.HasIndex("Mui_GiayID");

                    b.ToTable("san_Phams");
                });

            modelBuilder.Entity("ClssLib.San_Pham_Chi_Tiet", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Chat_LieuID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Co_GiayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Danh_MucID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("De_GiayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Kich_ThuocID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Kieu_DangID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Loai_GiayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Mau_SacID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Mui_GiayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("San_PhamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("gia")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<int>("so_luong")
                        .HasColumnType("int");

                    b.Property<string>("ten_SPCT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Chat_LieuID");

                    b.HasIndex("Co_GiayID");

                    b.HasIndex("Danh_MucID");

                    b.HasIndex("De_GiayID");

                    b.HasIndex("Kich_ThuocID");

                    b.HasIndex("Kieu_DangID");

                    b.HasIndex("Loai_GiayID");

                    b.HasIndex("Mau_SacID");

                    b.HasIndex("Mui_GiayID");

                    b.HasIndex("San_PhamID");

                    b.ToTable("san_Pham_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.Tai_Khoan", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Vai_TroID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cccd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("gioi_tinh")
                        .HasColumnType("int");

                    b.Property<string>("hinh_anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ho_ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_sinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("pass_word")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Vai_TroID");

                    b.ToTable("tai_Khoans");

                    b.HasData(
                        new
                        {
                            ID = new Guid("f9765ece-a7de-4f59-a1ad-910b9ca7fde7"),
                            Vai_TroID = new Guid("a318b59e-8235-49bd-9617-45ddc02ec9b5"),
                            cccd = "123456789012",
                            email = "admin_tong@fpt.edu.vn",
                            gioi_tinh = 1,
                            hinh_anh = "admin_tong.png",
                            ho_ten = "Admin Tổng",
                            ma = "ADMIN01",
                            ngay_sinh = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ngay_tao = new DateTime(2025, 4, 17, 8, 59, 47, 54, DateTimeKind.Local).AddTicks(1536),
                            pass_word = "Admin123",
                            sdt = "0123456789",
                            trang_thai = 1,
                            user_name = "admin_tong"
                        });
                });

            modelBuilder.Entity("ClssLib.Tai_Khoan_Hoa_Don", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Hoa_DonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Tai_KhoanID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("vai_tro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Hoa_DonID");

                    b.HasIndex("Tai_KhoanID");

                    b.ToTable("tai_Khoan_Hoa_Dons");
                });

            modelBuilder.Entity("ClssLib.Thanh_Toan", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Hoa_DonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Phuong_Thuc_Thanh_ToanID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_thanh_toan")
                        .HasColumnType("datetime2");

                    b.Property<double>("so_tien_thanh_toan")
                        .HasColumnType("float");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Hoa_DonID");

                    b.HasIndex("Phuong_Thuc_Thanh_ToanID");

                    b.ToTable("thanh_Toans");
                });

            modelBuilder.Entity("ClssLib.ThongKe", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DoanhThu")
                        .HasColumnType("datetime2");

                    b.Property<int>("DonHuy")
                        .HasColumnType("int");

                    b.Property<int>("DonThanhCong")
                        .HasColumnType("int");

                    b.Property<Guid>("Hoa_DonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("San_Pham_Chi_TietID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuongSP")
                        .HasColumnType("int");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Hoa_DonID");

                    b.HasIndex("San_Pham_Chi_TietID");

                    b.ToTable("thongKes");
                });

            modelBuilder.Entity("ClssLib.Vai_Tro", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten_vai_tro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("vai_Tros");

                    b.HasData(
                        new
                        {
                            ID = new Guid("a318b59e-8235-49bd-9617-45ddc02ec9b5"),
                            ngay_tao = new DateTime(2025, 4, 17, 8, 59, 47, 54, DateTimeKind.Local).AddTicks(1253),
                            ten_vai_tro = "Admin",
                            trang_thai = 1
                        },
                        new
                        {
                            ID = new Guid("9c206d8b-54d7-46cd-b21d-c713cb8a6d4a"),
                            ngay_tao = new DateTime(2025, 4, 17, 8, 59, 47, 54, DateTimeKind.Local).AddTicks(1274),
                            ten_vai_tro = "Nhân Viên",
                            trang_thai = 1
                        },
                        new
                        {
                            ID = new Guid("bbe189d8-ec50-4da5-ad96-f4946ac9dd81"),
                            ngay_tao = new DateTime(2025, 4, 17, 8, 59, 47, 54, DateTimeKind.Local).AddTicks(1287),
                            ten_vai_tro = "Khách hàng",
                            trang_thai = 1
                        });
                });

            modelBuilder.Entity("ClssLib.Anh_San_Pham", b =>
                {
                    b.HasOne("ClssLib.San_Pham", "San_Pham")
                        .WithMany("Anh_San_Phams")
                        .HasForeignKey("San_PhamID");

                    b.Navigation("San_Pham");
                });

            modelBuilder.Entity("ClssLib.Anh_San_Pham_San_Pham_Chi_Tiet", b =>
                {
                    b.HasOne("ClssLib.Anh_San_Pham", "Anh_San_Pham")
                        .WithMany("Anh_San_Pham_San_Pham_Chi_Tiets")
                        .HasForeignKey("Anh_San_PhamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.San_Pham_Chi_Tiet", "San_Pham_Chi_Tiet")
                        .WithMany("Anh_San_Pham_San_Pham_Chi_Tiets")
                        .HasForeignKey("San_Pham_Chi_TietID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anh_San_Pham");

                    b.Navigation("San_Pham_Chi_Tiet");
                });

            modelBuilder.Entity("ClssLib.Dia_Chi", b =>
                {
                    b.HasOne("ClssLib.Tai_Khoan", "Tai_Khoan")
                        .WithMany("Dia_Chi")
                        .HasForeignKey("Tai_KhoanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tai_Khoan");
                });

            modelBuilder.Entity("ClssLib.Hoa_Don", b =>
                {
                    b.HasOne("ClssLib.Phieu_Giam_Gia", "Giam_Gia")
                        .WithMany("Hoa_Dons")
                        .HasForeignKey("Giam_GiaID");

                    b.Navigation("Giam_Gia");
                });

            modelBuilder.Entity("ClssLib.Hoa_Don_Chi_Tiet", b =>
                {
                    b.HasOne("ClssLib.Hoa_Don", "Hoa_Don")
                        .WithMany("Hoa_Don_Chi_Tiets")
                        .HasForeignKey("Hoa_DonID");

                    b.HasOne("ClssLib.San_Pham_Chi_Tiet", "San_Pham_Chi_Tiet")
                        .WithMany("Hoa_Don_Chi_Tiets")
                        .HasForeignKey("San_Pham_Chi_TietID");

                    b.Navigation("Hoa_Don");

                    b.Navigation("San_Pham_Chi_Tiet");
                });

            modelBuilder.Entity("ClssLib.Phieu_Giam_Gia_Tai_Khoan", b =>
                {
                    b.HasOne("ClssLib.Phieu_Giam_Gia", "Phieu_Giam_Gia")
                        .WithMany("Phieu_Giam_Gia_Tai_Khoans")
                        .HasForeignKey("Phieu_Giam_GiaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Tai_Khoan", "Tai_Khoan")
                        .WithMany("Phieu_Giam_Gia_Tai_Khoans")
                        .HasForeignKey("Tai_KhoanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phieu_Giam_Gia");

                    b.Navigation("Tai_Khoan");
                });

            modelBuilder.Entity("ClssLib.San_Pham", b =>
                {
                    b.HasOne("ClssLib.Chat_Lieu", "Chat_Lieu")
                        .WithMany("San_Phams")
                        .HasForeignKey("Chat_LieuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Co_Giay", "Co_Giay")
                        .WithMany("San_Phams")
                        .HasForeignKey("Co_GiayID");

                    b.HasOne("ClssLib.Danh_Muc", "Danh_Muc")
                        .WithMany("San_Phams")
                        .HasForeignKey("Danh_MucID");

                    b.HasOne("ClssLib.De_Giay", "De_Giay")
                        .WithMany("San_Phams")
                        .HasForeignKey("De_GiayID");

                    b.HasOne("ClssLib.Kieu_Dang", "Kieu_Dang")
                        .WithMany("San_Phams")
                        .HasForeignKey("Kieu_DangID");

                    b.HasOne("ClssLib.Loai_Giay", "Loai_Giay")
                        .WithMany("San_Phams")
                        .HasForeignKey("Loai_GiayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Mui_Giay", "Mui_Giay")
                        .WithMany("San_Phams")
                        .HasForeignKey("Mui_GiayID");

                    b.Navigation("Chat_Lieu");

                    b.Navigation("Co_Giay");

                    b.Navigation("Danh_Muc");

                    b.Navigation("De_Giay");

                    b.Navigation("Kieu_Dang");

                    b.Navigation("Loai_Giay");

                    b.Navigation("Mui_Giay");
                });

            modelBuilder.Entity("ClssLib.San_Pham_Chi_Tiet", b =>
                {
                    b.HasOne("ClssLib.Chat_Lieu", "Chat_Lieu")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("Chat_LieuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Co_Giay", "Co_Giay")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("Co_GiayID");

                    b.HasOne("ClssLib.Danh_Muc", "Danh_Muc")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("Danh_MucID");

                    b.HasOne("ClssLib.De_Giay", "De_Giay")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("De_GiayID");

                    b.HasOne("ClssLib.Kich_Thuoc", "Kich_Thuoc")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("Kich_ThuocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Kieu_Dang", "Kieu_Dang")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("Kieu_DangID");

                    b.HasOne("ClssLib.Loai_Giay", "Loai_Giay")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("Loai_GiayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Mau_Sac", "Mau_Sac")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("Mau_SacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Mui_Giay", "Mui_Giay")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("Mui_GiayID");

                    b.HasOne("ClssLib.San_Pham", "San_Pham")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("San_PhamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat_Lieu");

                    b.Navigation("Co_Giay");

                    b.Navigation("Danh_Muc");

                    b.Navigation("De_Giay");

                    b.Navigation("Kich_Thuoc");

                    b.Navigation("Kieu_Dang");

                    b.Navigation("Loai_Giay");

                    b.Navigation("Mau_Sac");

                    b.Navigation("Mui_Giay");

                    b.Navigation("San_Pham");
                });

            modelBuilder.Entity("ClssLib.Tai_Khoan", b =>
                {
                    b.HasOne("ClssLib.Vai_Tro", "Vai_Tro")
                        .WithMany("tai_Khoans")
                        .HasForeignKey("Vai_TroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vai_Tro");
                });

            modelBuilder.Entity("ClssLib.Tai_Khoan_Hoa_Don", b =>
                {
                    b.HasOne("ClssLib.Hoa_Don", "Hoa_Don")
                        .WithMany("Tai_Khoan_Hoa_Dons")
                        .HasForeignKey("Hoa_DonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Tai_Khoan", "Tai_Khoan")
                        .WithMany("Tai_Khoan_Hoa_Don")
                        .HasForeignKey("Tai_KhoanID");

                    b.Navigation("Hoa_Don");

                    b.Navigation("Tai_Khoan");
                });

            modelBuilder.Entity("ClssLib.Thanh_Toan", b =>
                {
                    b.HasOne("ClssLib.Hoa_Don", "Hoa_Don")
                        .WithMany("Thanh_Toans")
                        .HasForeignKey("Hoa_DonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Phuong_Thuc_Thanh_Toan", "Phuong_Thuc_Thanh_Toan")
                        .WithMany("Thanh_Toans")
                        .HasForeignKey("Phuong_Thuc_Thanh_ToanID");

                    b.Navigation("Hoa_Don");

                    b.Navigation("Phuong_Thuc_Thanh_Toan");
                });

            modelBuilder.Entity("ClssLib.ThongKe", b =>
                {
                    b.HasOne("ClssLib.Hoa_Don", "Hoa_Don")
                        .WithMany()
                        .HasForeignKey("Hoa_DonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.San_Pham_Chi_Tiet", "San_Pham_Chi_Tiet")
                        .WithMany()
                        .HasForeignKey("San_Pham_Chi_TietID");

                    b.Navigation("Hoa_Don");

                    b.Navigation("San_Pham_Chi_Tiet");
                });

            modelBuilder.Entity("ClssLib.Anh_San_Pham", b =>
                {
                    b.Navigation("Anh_San_Pham_San_Pham_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.Chat_Lieu", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");

                    b.Navigation("San_Phams");
                });

            modelBuilder.Entity("ClssLib.Co_Giay", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");

                    b.Navigation("San_Phams");
                });

            modelBuilder.Entity("ClssLib.Danh_Muc", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");

                    b.Navigation("San_Phams");
                });

            modelBuilder.Entity("ClssLib.De_Giay", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");

                    b.Navigation("San_Phams");
                });

            modelBuilder.Entity("ClssLib.Hoa_Don", b =>
                {
                    b.Navigation("Hoa_Don_Chi_Tiets");

                    b.Navigation("Tai_Khoan_Hoa_Dons");

                    b.Navigation("Thanh_Toans");
                });

            modelBuilder.Entity("ClssLib.Kich_Thuoc", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.Kieu_Dang", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");

                    b.Navigation("San_Phams");
                });

            modelBuilder.Entity("ClssLib.Loai_Giay", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");

                    b.Navigation("San_Phams");
                });

            modelBuilder.Entity("ClssLib.Mau_Sac", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.Mui_Giay", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");

                    b.Navigation("San_Phams");
                });

            modelBuilder.Entity("ClssLib.Phieu_Giam_Gia", b =>
                {
                    b.Navigation("Hoa_Dons");

                    b.Navigation("Phieu_Giam_Gia_Tai_Khoans");
                });

            modelBuilder.Entity("ClssLib.Phuong_Thuc_Thanh_Toan", b =>
                {
                    b.Navigation("Thanh_Toans");
                });

            modelBuilder.Entity("ClssLib.San_Pham", b =>
                {
                    b.Navigation("Anh_San_Phams");

                    b.Navigation("San_Pham_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.San_Pham_Chi_Tiet", b =>
                {
                    b.Navigation("Anh_San_Pham_San_Pham_Chi_Tiets");

                    b.Navigation("Hoa_Don_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.Tai_Khoan", b =>
                {
                    b.Navigation("Dia_Chi");

                    b.Navigation("Phieu_Giam_Gia_Tai_Khoans");

                    b.Navigation("Tai_Khoan_Hoa_Don");
                });

            modelBuilder.Entity("ClssLib.Vai_Tro", b =>
                {
                    b.Navigation("tai_Khoans");
                });
#pragma warning restore 612, 618
        }
    }
}
