// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanGiay.Data;

#nullable disable

namespace WebBanGiay.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClssLib.Anh_San_Pham", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("San_Pham_Chi_TietID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("anh_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("San_Pham_Chi_TietID");

                    b.ToTable("anh_San_Phams");
                });

            modelBuilder.Entity("ClssLib.Chat_Lieu", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_chat_lieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("chat_Lieus");
                });

            modelBuilder.Entity("ClssLib.Co_Giay", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_loai_co_giay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("co_Giays");
                });

            modelBuilder.Entity("ClssLib.Danh_Muc", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_danh_muc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("danh_Mucs");
                });

            modelBuilder.Entity("ClssLib.De_Giay", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_de_giay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("de_Giays");
                });

            modelBuilder.Entity("ClssLib.Dia_Chi", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Khach_HangID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("huyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("loai_dia_chi")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("tinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Khach_HangID");

                    b.ToTable("dia_Chis");
                });

            modelBuilder.Entity("ClssLib.Hoa_Don", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Giam_GiaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Khach_HangID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Nhan_VienID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("dia_chi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email_nguoi_nhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ghi_chu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("loai_hoa_don")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("nguoi_sua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt_nguoi_nhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_nguoi_nhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("thoi_gian_nhan_hang")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("tong_tien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Giam_GiaID");

                    b.HasIndex("Khach_HangID");

                    b.HasIndex("Nhan_VienID");

                    b.ToTable("hoa_Dons");
                });

            modelBuilder.Entity("ClssLib.Hoa_Don_Chi_Tiet", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Hoa_DonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("nguoi_sua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("so_luong")
                        .HasColumnType("int");

                    b.Property<decimal>("thanh_tien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Hoa_DonID");

                    b.ToTable("don_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.Khach_Hang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Tai_KhoanID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("gioi_tinh")
                        .HasColumnType("int");

                    b.Property<string>("ho_ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ngay_sinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Tai_KhoanID")
                        .IsUnique();

                    b.ToTable("khach_Hangs");
                });

            modelBuilder.Entity("ClssLib.Kich_Thuoc", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_kich_thuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("kich_Thuocs");
                });

            modelBuilder.Entity("ClssLib.Kieu_Dang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_kieu_dang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("kieu_Dangs");
                });

            modelBuilder.Entity("ClssLib.Loai_Giay", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_loai_giay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("loai_Giays");
                });

            modelBuilder.Entity("ClssLib.Mau_Sac", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_mau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("mau_Sacs");
                });

            modelBuilder.Entity("ClssLib.Mui_Giay", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_mui_giay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("mui_Giays");
                });

            modelBuilder.Entity("ClssLib.Nhan_Vien", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Tai_KhoanID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cccd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("gioi_tinh")
                        .HasColumnType("int");

                    b.Property<string>("ho_ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ngay_sinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Tai_KhoanID")
                        .IsUnique()
                        .HasFilter("[Tai_KhoanID] IS NOT NULL");

                    b.ToTable("nhan_Viens");
                });

            modelBuilder.Entity("ClssLib.Phieu_Giam_Gia", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("gia_tri_giam")
                        .HasColumnType("int");

                    b.Property<decimal>("gia_tri_toi_thieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("kieu_giam_gia")
                        .HasColumnType("int");

                    b.Property<int>("loai_phieu_giam_gia")
                        .HasColumnType("int");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_bat_dau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_ket_thuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("nguoi_sua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("so_luong")
                        .HasColumnType("int");

                    b.Property<int>("so_tien_giam_toi_da")
                        .HasColumnType("int");

                    b.Property<string>("ten_phieu_giam_gia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("phieu_Giam_Gias");
                });

            modelBuilder.Entity("ClssLib.Phieu_Giam_Gia_Khach_Hang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Khach_HangID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Phieu_Giam_GiaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("nguoi_sua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Khach_HangID");

                    b.HasIndex("Phieu_Giam_GiaID");

                    b.ToTable("giam_Gia_Khach_Hangs");
                });

            modelBuilder.Entity("ClssLib.Phuong_Thuc_Thanh_Toan", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_phuong_thuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("phuong_Thuc_Thanh_Toans");
                });

            modelBuilder.Entity("ClssLib.San_Pham", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("nguoi_sua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_san_pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("san_Phams");
                });

            modelBuilder.Entity("ClssLib.San_Pham_Chi_Tiet", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Chat_LieuID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Co_GiayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Danh_MucID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("De_GiayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Kich_ThuocID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Kieu_DangID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Loai_GiayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Mau_SacID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Mui_GiayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("so_luong")
                        .HasColumnType("int");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Chat_LieuID");

                    b.HasIndex("Co_GiayID");

                    b.HasIndex("Danh_MucID");

                    b.HasIndex("De_GiayID");

                    b.HasIndex("Kich_ThuocID");

                    b.HasIndex("Kieu_DangID");

                    b.HasIndex("Loai_GiayID");

                    b.HasIndex("Mau_SacID");

                    b.HasIndex("Mui_GiayID");

                    b.ToTable("san_Pham_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.Tai_Khoan", b =>
                {
                    b.Property<Guid>("Tai_KhoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ngay_sua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("pass_word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten_vai_tro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Tai_KhoanID");

                    b.ToTable("tai_Khoans");
                });

            modelBuilder.Entity("ClssLib.Thanh_Toan", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Hoa_DonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Phuong_Thuc_Thanh_ToanID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngay_thanh_toan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("so_tien_thanh_toan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("trang_thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Hoa_DonID");

                    b.HasIndex("Phuong_Thuc_Thanh_ToanID");

                    b.ToTable("thanh_Toans");
                });

            modelBuilder.Entity("ClssLib.Anh_San_Pham", b =>
                {
                    b.HasOne("ClssLib.San_Pham_Chi_Tiet", "San_Pham_Chi_Tiet")
                        .WithMany("Anh_San_Phams")
                        .HasForeignKey("San_Pham_Chi_TietID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("San_Pham_Chi_Tiet");
                });

            modelBuilder.Entity("ClssLib.Dia_Chi", b =>
                {
                    b.HasOne("ClssLib.Khach_Hang", "Khach_Hang")
                        .WithMany("Dia_Chi")
                        .HasForeignKey("Khach_HangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khach_Hang");
                });

            modelBuilder.Entity("ClssLib.Hoa_Don", b =>
                {
                    b.HasOne("ClssLib.Phieu_Giam_Gia", "Giam_Gia")
                        .WithMany("Hoa_Dons")
                        .HasForeignKey("Giam_GiaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Khach_Hang", "Khach_Hang")
                        .WithMany("Hoa_Dons")
                        .HasForeignKey("Khach_HangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Nhan_Vien", "Nhan_Vien")
                        .WithMany("Hoa_Dons")
                        .HasForeignKey("Nhan_VienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Giam_Gia");

                    b.Navigation("Khach_Hang");

                    b.Navigation("Nhan_Vien");
                });

            modelBuilder.Entity("ClssLib.Hoa_Don_Chi_Tiet", b =>
                {
                    b.HasOne("ClssLib.Hoa_Don", "Hoa_Don")
                        .WithMany("Hoa_Don_Chi_Tiets")
                        .HasForeignKey("Hoa_DonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hoa_Don");
                });

            modelBuilder.Entity("ClssLib.Khach_Hang", b =>
                {
                    b.HasOne("ClssLib.Tai_Khoan", "Tai_Khoan")
                        .WithOne("Khach_Hang")
                        .HasForeignKey("ClssLib.Khach_Hang", "Tai_KhoanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tai_Khoan");
                });

            modelBuilder.Entity("ClssLib.Nhan_Vien", b =>
                {
                    b.HasOne("ClssLib.Tai_Khoan", "Tai_Khoan")
                        .WithOne("Nhan_Vien")
                        .HasForeignKey("ClssLib.Nhan_Vien", "Tai_KhoanID");

                    b.Navigation("Tai_Khoan");
                });

            modelBuilder.Entity("ClssLib.Phieu_Giam_Gia_Khach_Hang", b =>
                {
                    b.HasOne("ClssLib.Khach_Hang", "Khach_Hang")
                        .WithMany()
                        .HasForeignKey("Khach_HangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Phieu_Giam_Gia", "Phieu_Giam_Gia")
                        .WithMany("Phieu_Giam_Gia_Khach_Hang")
                        .HasForeignKey("Phieu_Giam_GiaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khach_Hang");

                    b.Navigation("Phieu_Giam_Gia");
                });

            modelBuilder.Entity("ClssLib.San_Pham_Chi_Tiet", b =>
                {
                    b.HasOne("ClssLib.Chat_Lieu", "Chat_Lieu")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("Chat_LieuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Co_Giay", "Co_Giay")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("Co_GiayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Danh_Muc", "Danh_Muc")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("Danh_MucID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.De_Giay", "De_Giay")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("De_GiayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Kich_Thuoc", "Kich_Thuoc")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("Kich_ThuocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Kieu_Dang", "Kieu_Dang")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("Kieu_DangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Loai_Giay", "Loai_Giay")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("Loai_GiayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Mau_Sac", "Mau_Sac")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("Mau_SacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Mui_Giay", "Mui_Giay")
                        .WithMany("San_Pham_Chi_Tiets")
                        .HasForeignKey("Mui_GiayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat_Lieu");

                    b.Navigation("Co_Giay");

                    b.Navigation("Danh_Muc");

                    b.Navigation("De_Giay");

                    b.Navigation("Kich_Thuoc");

                    b.Navigation("Kieu_Dang");

                    b.Navigation("Loai_Giay");

                    b.Navigation("Mau_Sac");

                    b.Navigation("Mui_Giay");
                });

            modelBuilder.Entity("ClssLib.Thanh_Toan", b =>
                {
                    b.HasOne("ClssLib.Hoa_Don", "Hoa_Don")
                        .WithMany("Thanh_Toans")
                        .HasForeignKey("Hoa_DonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClssLib.Phuong_Thuc_Thanh_Toan", "Phuong_Thuc_Thanh_Toan")
                        .WithMany("Thanh_Toans")
                        .HasForeignKey("Phuong_Thuc_Thanh_ToanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hoa_Don");

                    b.Navigation("Phuong_Thuc_Thanh_Toan");
                });

            modelBuilder.Entity("ClssLib.Chat_Lieu", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.Co_Giay", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.Danh_Muc", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.De_Giay", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.Hoa_Don", b =>
                {
                    b.Navigation("Hoa_Don_Chi_Tiets");

                    b.Navigation("Thanh_Toans");
                });

            modelBuilder.Entity("ClssLib.Khach_Hang", b =>
                {
                    b.Navigation("Dia_Chi");

                    b.Navigation("Hoa_Dons");
                });

            modelBuilder.Entity("ClssLib.Kich_Thuoc", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.Kieu_Dang", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.Loai_Giay", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.Mau_Sac", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.Mui_Giay", b =>
                {
                    b.Navigation("San_Pham_Chi_Tiets");
                });

            modelBuilder.Entity("ClssLib.Nhan_Vien", b =>
                {
                    b.Navigation("Hoa_Dons");
                });

            modelBuilder.Entity("ClssLib.Phieu_Giam_Gia", b =>
                {
                    b.Navigation("Hoa_Dons");

                    b.Navigation("Phieu_Giam_Gia_Khach_Hang");
                });

            modelBuilder.Entity("ClssLib.Phuong_Thuc_Thanh_Toan", b =>
                {
                    b.Navigation("Thanh_Toans");
                });

            modelBuilder.Entity("ClssLib.San_Pham_Chi_Tiet", b =>
                {
                    b.Navigation("Anh_San_Phams");
                });

            modelBuilder.Entity("ClssLib.Tai_Khoan", b =>
                {
                    b.Navigation("Khach_Hang");

                    b.Navigation("Nhan_Vien");
                });
#pragma warning restore 612, 618
        }
    }
}
